swagger: "2.0"
info:
  title: Bank Argent Transactions API
  description: API endpoints for managing bank transactions
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /transactions/monthly:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: View Monthly Transactions
      description: API for viewing all transactions for the current month, grouped by account
      produces:
        - application/json
      responses:
        "200":
          description: Monthly transactions retrieved successfully
          schema:
            $ref: "#/definitions/TransactionsList"
        "400":
          description: Invalid Request
        "401":
          description: Unauthorized Access
        "500":
          description: Internal Server Error
  /transaction/{transactionId}:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: View Transaction Details
      description: API for viewing the details of a specific transaction
      parameters:
        - in: path
          name: transactionId
          required: true
          type: string
          description: Unique ID of the transaction
      produces:
        - application/json
      responses:
        "200":
          description: Transaction details retrieved successfully
          schema:
            $ref: "#/definitions/TransactionDetail"
        "400":
          description: Invalid Transaction ID
        "401":
          description: Unauthorized Access
        "404":
          description: Transaction Not Found
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Modify Transaction
      description: API for modifying a transaction
      parameters:
        - in: path
          name: transactionId
          required: true
          type: string
          description: Unique ID of the transaction
        - in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/TransactionUpdate"
      produces:
        - application/json
      responses:
        "200":
          description: Transaction updated successfully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields or Transaction ID
        "401":
          description: Unauthorized Access
        "404":
          description: Transaction Not Found
        "500":
          description: Internal Server Error
    delete:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Delete Transaction
      description: API for deleting a transaction
      parameters:
        - in: path
          name: transactionId
          required: true
          type: string
          description: Unique ID of the transaction
      produces:
        - application/json
      responses:
        "200":
          description: Transaction deleted successfully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Transaction ID
        "401":
          description: Unauthorized Access
        "404":
          description: Transaction Not Found
        "500":
          description: Internal Server Error
  /transaction:
    post:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Add Transaction
      description: API for adding a new transaction
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/TransactionCreate"
      produces:
        - application/json
      responses:
        "201":
          description: Transaction created successfully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "401":
          description: Unauthorized Access
        "500":
          description: Internal Server Error
  /transaction/{transactionId}/category:
    put:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Update Transaction Category
      description: API for updating the category of a transaction
      parameters:
        - in: path
          name: transactionId
          required: true
          type: string
          description: Unique ID of the transaction
        - in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/TransactionCategoryUpdate"
      produces:
        - application/json
      responses:
        "200":
          description: Transaction category updated successfully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Request
        "401":
          description: Unauthorized Access
        "404":
          description: Transaction Not Found
        "500":
          description: Internal Server Error
  /transaction/{transactionId}/note:
    put:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Update Transaction Note
      description: API for adding or updating a note to a transaction
      parameters:
        - in: path
          name: transactionId
          required: true
          type: string
          description: Unique ID of the transaction
        - in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/TransactionNoteUpdate"
      produces:
        - application/json
      responses:
        "200":
          description: Transaction note updated successfully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Request
        "401":
          description: Unauthorized Access
        "404":
          description: Transaction Not Found
        "500":
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  TransactionCreate:
    type: object
    required:
      - accountId
      - amount
      - type
    properties:
      accountId:
        type: string
        description: Unique ID of the account
      amount:
        type: number
        description: Transaction amount
      type:
        type: string
        enum:
          - debit
          - credit
      description:
        type: string
        description: Transaction description
  TransactionUpdate:
    type: object
    properties:
      amount:
        type: number
        description: Updated transaction amount
      description:
        type: string
        description: Updated transaction description
  TransactionCategoryUpdate:
    type: object
    required:
      - category
    properties:
      category:
        type: string
        description: New category for the transaction
  TransactionNoteUpdate:
    type: object
    required:
      - note
    properties:
      note:
        type: string
        description: Note to be added or updated for the transaction
  TransactionsList:
    type: array
    items:
      $ref: "#/definitions/TransactionDetail"
  TransactionDetail:
    type: object
    properties:
      id:
        type: string
        description: Unique ID of the transaction
      accountId:
        type: string
        description: Unique ID of the account
      amount:
        type: number
        description: Transaction amount
      type:
        type: string
        description: Transaction type
      description:
        type: string
        description: Transaction description
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          message:
            type: string
