swagger: "2.0"
info:
  title: Bank Argent Transactions API
  description: API endpoints for managing bank transactions, focusing on security and detailed transaction information.
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /transactions/monthly:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: View Monthly Transactions
      description: API for viewing all transactions for the current month, grouped by account.
      produces:
        - application/json
      responses:
        "200":
          description: Monthly transactions retrieved successfully
          schema:
            $ref: "#/definitions/TransactionsList"
        "400":
          description: Invalid Request
        "401":
          description: Unauthorized Access
        "500":
          description: Internal Server Error

  /transaction/{transactionId}:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: View Transaction Details
      description: API for viewing the details of a specific transaction.
      parameters:
        - in: path
          name: transactionId
          required: true
          type: string
          description: Unique ID of the transaction
      produces:
        - application/json
      responses:
        "200":
          description: Transaction details retrieved successfully
          schema:
            $ref: "#/definitions/TransactionDetail"
        "400":
          description: Invalid Transaction ID
        "401":
          description: Unauthorized Access
        "404":
          description: Transaction Not Found
        "500":
          description: Internal Server Error

  /transaction/{transactionId}/category:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Get Transaction Category
      description: API for getting the category of a specific transaction.
      parameters:
        - in: path
          name: transactionId
          required: true
          type: string
          description: Unique ID of the transaction
      responses:
        "200":
          description: Transaction category retrieved successfully
          schema:
            type: object
            properties:
              category:
                type: string
                description: Category of the transaction
        "400":
          description: Invalid Request
        "401":
          description: Unauthorized Access
        "404":
          description: Transaction Not Found
        "500":
          description: Internal Server Error
    post:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Add a new category to a transaction
      description: API for adding a new category to a transaction.
      parameters:
        - in: path
          name: transactionId
          required: true
          type: string
          description: Unique ID of the transaction
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              category:
                type: string
                description: New category to be added
      responses:
        "201":
          description: New category added to transaction successfully
        "400":
          description: Invalid Request
        "401":
          description: Unauthorized Access
        "404":
          description: Transaction Not Found
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Update Transaction Category
      description: API for updating the category of a transaction.
      parameters:
        - in: path
          name: transactionId
          required: true
          type: string
          description: Unique ID of the transaction
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              category:
                type: string
                description: Updated category for the transaction
      responses:
        "200":
          description: Transaction category updated successfully
        "400":
          description: Invalid Request
        "401":
          description: Unauthorized Access
        "404":
          description: Transaction Not Found
        "500":
          description: Internal Server Error
    delete:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Delete Transaction Category
      description: API for deleting the category of a transaction.
      parameters:
        - in: path
          name: transactionId
          required: true
          type: string
          description: Unique ID of the transaction
      responses:
        "200":
          description: Transaction category deleted successfully
        "400":
          description: Invalid Request
        "401":
          description: Unauthorized Access
        "404":
          description: Transaction Not Found
        "500":
          description: Internal Server Error

  /transaction/{transactionId}/note:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Get Transaction Note
      description: API for getting the note of a specific transaction.
      parameters:
        - in: path
          name: transactionId
          required: true
          type: string
          description: Unique ID of the transaction
      responses:
        "200":
          description: Transaction note retrieved successfully
          schema:
            type: object
            properties:
              note:
                type: string
                description: Note of the transaction
        "400":
          description: Invalid Request
        "401":
          description: Unauthorized Access
        "404":
          description: Transaction Not Found
        "500":
          description: Internal Server Error
    post:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Add a new note to a transaction
      description: API for adding a new note to a transaction.
      parameters:
        - in: path
          name: transactionId
          required: true
          type: string
          description: Unique ID of the transaction
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              note:
                type: string
                description: New note to be added
      responses:
        "201":
          description: New note added to transaction successfully
        "400":
          description: Invalid Request
        "401":
          description: Unauthorized Access
        "404":
          description: Transaction Not Found
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Update Transaction Note
      description: API for updating a note of a transaction.
      parameters:
        - in: path
          name: transactionId
          required: true
          type: string
          description: Unique ID of the transaction
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              note:
                type: string
                description: Updated note for the transaction
      responses:
        "200":
          description: Transaction note updated successfully
        "400":
          description: Invalid Request
        "401":
          description: Unauthorized Access
        "404":
          description: Transaction Not Found
        "500":
          description: Internal Server Error
    delete:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Delete Transaction Note
      description: API for deleting a note from a transaction.
      parameters:
        - in: path
          name: transactionId
          required: true
          type: string
          description: Unique ID of the transaction
      responses:
        "200":
          description: Transaction note deleted successfully
        "400":
          description: Invalid Request
        "401":
          description: Unauthorized Access
        "404":
          description: Transaction Not Found
        "500":
          description: Internal Server Error

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

definitions:
  TransactionsList:
    type: array
    items:
      $ref: "#/definitions/TransactionDetail"
  TransactionDetail:
    type: object
    properties:
      id:
        type: string
        description: Unique ID of the transaction
      date:
        type: string
        format: date
        description: Date of the transaction
      description:
        type: string
        description: Description of the transaction
      amount:
        type: number
        format: double
        description: Amount spent in the transaction
      availableBalance:
        type: number
        format: double
        description: Available balance after the transaction was made
      type:
        type: string
        description: Type of transaction (e.g., debit, credit)
  TransactionCategoryUpdate:
    type: object
    required:
      - category
    properties:
      category:
        type: string
        description: New or updated category for the transaction
  TransactionNoteUpdate:
    type: object
    required:
      - note
    properties:
      note:
        type: string
        description: New or updated note for the transaction
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          message:
            type: string
