swagger: "2.0"
info:
  title: Bank Argent Transactions API
  description: API endpoints for managing bank transactions, focusing on security and detailed transaction information.
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /transactions/monthly:
    post:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: View Monthly Transactions
      description: API for securely viewing all transactions for the current month, grouped by account. Uses a POST method for enhanced security.
      parameters:
        - in: body
          name: body
          description: Request parameters for viewing monthly transactions
          required: true
          schema:
            type: object
            properties:
              accountId:
                type: string
                description: Unique ID of the account to filter transactions
      produces:
        - application/json
      responses:
        "200":
          description: Monthly transactions retrieved successfully
          schema:
            $ref: "#/definitions/TransactionsList"
        "400":
          description: Invalid Request
        "401":
          description: Unauthorized Access
        "500":
          description: Internal Server Error
  /transaction/{transactionId}:
    post:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: View Transaction Details
      description: API for securely viewing the details of a specific transaction using a POST method.
      parameters:
        - in: path
          name: transactionId
          required: true
          type: string
          description: Unique ID of the transaction
        - in: body
          name: body
          description: Request parameters for viewing a transaction detail
          required: true
          schema:
            type: object
            properties:
              detailLevel:
                type: string
                description: Level of detail requested for the transaction
      produces:
        - application/json
      responses:
        "200":
          description: Transaction details retrieved successfully
          schema:
            $ref: "#/definitions/TransactionDetail"
        "400":
          description: Invalid Transaction ID
        "401":
          description: Unauthorized Access
        "404":
          description: Transaction Not Found
        "500":
          description: Internal Server Error
  /transaction/{transactionId}/category:
    put:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Update Transaction Category
      description: API for updating the category of a transaction.
      parameters:
        - in: path
          name: transactionId
          required: true
          type: string
          description: Unique ID of the transaction
        - in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/TransactionCategoryUpdate"
      produces:
        - application/json
      responses:
        "200":
          description: Transaction category updated successfully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Request
        "401":
          description: Unauthorized Access
        "404":
          description: Transaction Not Found
        "500":
          description: Internal Server Error
  /transaction/{transactionId}/note:
    put:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Update Transaction Note
      description: API for adding or updating a note to a transaction.
      parameters:
        - in: path
          name: transactionId
          required: true
          type: string
          description: Unique ID of the transaction
        - in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/TransactionNoteUpdate"
      produces:
        - application/json
      responses:
        "200":
          description: Transaction note updated successfully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Request
        "401":
          description: Unauthorized Access
        "404":
          description: Transaction Not Found
        "500":
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  TransactionCategoryUpdate:
    type: object
    required:
      - category
    properties:
      category:
        type: string
        description: New category for the transaction
  TransactionNoteUpdate:
    type: object
    required:
      - note
    properties:
      note:
        type: string
        description: Note to be added or updated for the transaction
  TransactionsList:
    type: array
    items:
      $ref: "#/definitions/TransactionDetail"
  TransactionDetail:
    type: object
    properties:
      id:
        type: string
        description: Unique ID of the transaction
      date:
        type: string
        format: date
        description: Date of the transaction
      description:
        type: string
        description: Description of the transaction
      amount:
        type: number
        format: double
        description: Amount spent in the transaction
      availableBalance:
        type: number
        format: double
        description: Available balance after the transaction was made
      type:
        type: string
        description: Type of transaction (e.g., debit, credit)
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          message:
            type: string
